from django.contrib import admin
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from digestapi.views import BookViewSet, UserViewSet, CategoryViewSet, ReviewViewSet

# Create a router for registering viewsets with automatic URL routing
router = DefaultRouter(trailing_slash=False)

# Register the BookViewSet with the router, specifying the base name as 'book'
router.register(r'books', BookViewSet, 'book')

# Register the CategoryViewSet with the router, specifying the base name as 'category'
router.register(r'categories', CategoryViewSet, 'category')

# Register the ReviewViewSet with the router, specifying the base name as 'review'
router.register(r'reviews', ReviewViewSet, 'review')

# Define the urlpatterns for the Django application
urlpatterns = [
    # Include the URLs generated by the router, adding them to the root path ('')
    path('', include(router.urls)),
    
    # Define a path for user login, mapped to the 'user_login' action in the UserViewSet
    path('login', UserViewSet.as_view({'post': 'user_login'}), name='login'),
    
    # Define a path for user registration, mapped to the 'register_account' action in the UserViewSet
    path('register', UserViewSet.as_view({'post': 'register_account'}), name='register'),
]
